#!/bin/bash
#
#######################################################################
# TRIOS Image writer                                                  #
# Simple dd wrapper. Uses zenity for GUI dialogs and pv for progress. #
#                                                                     #
# 2015 Filip Danilovic <filip@openmailbox.org>                        #
#                                                                     #
# This is free software. Licenced under GPL v2 or later. :)           #
#######################################################################

show_usage() {
			
	echo -e "\n*******************\nTRIOS Image Writer:\n*******************\n"
	echo -e "Asks the user to select an image file and a destination drive,
then, while showing progress, writes that image to it using good old dd. :)"
	echo -e "\nAccepts the following arguments:"
	echo " -f /path/to/image/file"
	echo " -d /dev/sdX"
	echo -e "\nDefault dd flags used are \"bs=4M\" and \"oflag=dsync\" "
	echo -e "\n2015 Filip Danilovic <filip@openmailbox.org>\n"
	exit
}

while getopts "h?f:d:" arg; do
    case "$arg" in
		f)
		ISO="$OPTARG"
		;;
		d)
		USB=$OPTARG
		;;
		h\?)
		show_usage
		;;
		*)
		show_usage
		;;
	esac
done

# Check zenity version:

ZENITY_V_MAJOR=`zenity --version | cut -d. -f1`
ZENITY_V_MINOR=`zenity --version | cut -d. -f2`

ZENITY_DEF_CANCEL=" "

echo -e "\nUsing zenity v$ZENITY_V_MAJOR.$ZENITY_V_MINOR.*\n"

if [ -z $ZENITY_V_MAJOR ]; then
	echo -e "\n!!!Zenity did not return it's version! It's probably not installed!!!\n"
	exit
fi

if [ "$ZENITY_V_MAJOR" -eq "3" -a "$ZENITY_V_MINOR" -ge "12" ]; then
	ZENITY_DEF_CANCEL="--default-cancel"
fi

if [ -z "$ISO" ]; then
	ISO=$(zenity --file-selection --title="Select image to write:")
	if [ -z "$ISO" ]; then
		exit
	fi
fi

SIZE=$(du -h -B1 "$ISO" | awk '{print $1}')


# zenity --info --text="$(echo "$SIZE\n$ISO")"

drive_select() {
# Make a temporary file
list=$(mktemp /tmp/XXXXXX)

# get a list of devices
devs=`ls -al /dev/disk/by-path/*usb*part* 2>/dev/null | awk '{print($11)}'`
if [[ ${?} != 0 || -z ${devs} ]]
then
    zenity --warning --text "No USB Pluged!"
    exit
fi

# Initialize list and make sure it is empty
>$list

# Now get the info about our devices and put it in a list
for dev in $devs; do dev="${dev##*\/}";
    echo "FALSE" >> $list;
    echo "/dev/${dev}" >> $list;
    echo `cat /sys/block/${dev:0:3}/device/vendor 2>/dev/null` >> $list;
    echo `cat /sys/block/${dev:0:3}/device/model 2>/dev/null` >> $list;
    echo `lsblk 2>/dev/null | grep \`echo -E ${dev}\` |awk '{print($4)}' `B >> $list;
    echo `lsblk 2>/dev/null | grep \`echo -E ${dev}\` |cut -c 37- ` >> $list;
    echo -n `lsblk -o NAME 2>/dev/null | grep \`echo -E ${dev}\`| awk '{print($2)}'  ` >> $list;
    df -T `echo -E /dev/${dev}` 2>/dev/null | tail -1 | awk '{print $2}' >> $list;
    echo `ls -l /dev/disk/by-uuid/ 2>/dev/null | grep \`echo -E ${dev}\`| awk '{print($9)}' ` >> $list;
        done
        
#Display the selection dialog
USB=$(cat ${list} | zenity --list --text="$(echo "Selected image is:\n$ISO\n" \
&& echo "<b>Pick</b> the target USB drive on the list bellow and click OK to proceed".)" \
 --radiolist  --width=650 --height=350 --column="Pick" --column="Dev" --column="Vendor" --column="Model" \
 --column="Size" --column="Mount" --column="FS" --column="UUID" --ok-label=Continue --cancel-label=Quit)
 
#Test for cancellation
if [[ ${?} != 0  ]]
then
rm $list
    exit 0
fi

rm $list

#Check if anything was selected
echo ${USB} | grep ^/dev/. &>/dev/null
if [[ ${?} != 0  ]]
then
    zenity --info --text="Nothing was selected..."
    exit 0
fi

}

if [ -z "$USB" ]; then
	drive_select
fi

check() {

	USB_INFO=$(lsblk "$USB" -o NAME,MODEL,VENDOR,SIZE)
	zenity --question "$ZENITY_DEF_CANCEL" --title="Safety check" \
		--text="$(echo "<b>Selected image is:</b>\n$ISO" && echo "\n
<b>Destination drive is \"$USB\".</b>\nDetails: \n$USB_INFO" && echo "\n
<b><u>Start writing?</u></b>")"

	if [[ $? == 0 ]] ; then
		write "$ISO" "$SIZE" "$USB"
	fi
}

#-------------------
#****************
# Write function:
#****************

write() {

	`dirname $0`/tiw-worker "$1" "$2" "$3"

}
#-------------------

if [ -b "$USB" ] ; then
	check
elif [[ "$USB" == "/dev/null" ]]; then
	check
else
	while [ ! -b "$USB" ]
	do
	zenity --question --ok-label=Retry --cancel-label=Quit --title="Error" \
		--text="$(echo "<b>\"$USB\" doesn\'t exist!</b>\nCheck your input.")"
	if [[ $? == 0 ]]; then
		drive_select
	else
		exit
	fi
	done
	check
fi

